"""initial schema

Revision ID: bed3561efe1d
Revises:
Create Date: 2026-04-05 21:37:25.994994

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('sales_area', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_country'), 'customers', ['country'], unique=False)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_table('standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ac_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('replaced_by', sa.String(length=100), nullable=True),
    sa.Column('normalized_code', sa.String(length=100), nullable=False),
    sa.Column('base_number', sa.String(length=50), nullable=False),
    sa.Column('version_year', sa.Integer(), nullable=True),
    sa.Column('committee', sa.String(length=100), nullable=True),
    sa.Column('ics_code', sa.String(length=20), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_ac_code'), 'standards', ['ac_code'], unique=True)
    op.create_index(op.f('ix_standards_base_number'), 'standards', ['base_number'], unique=False)
    op.create_index(op.f('ix_standards_status'), 'standards', ['status'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','expiring','expired','suspended')", name='ck_certificates_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index(op.f('ix_certificates_customer_id'), 'certificates', ['customer_id'], unique=False)
    op.create_index(op.f('ix_certificates_expiry_date'), 'certificates', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_certificates_status'), 'certificates', ['status'], unique=False)
    op.create_table('cert_standard_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('standard_ref', sa.String(length=200), nullable=False),
    sa.Column('normalized_ref', sa.String(length=200), nullable=False),
    sa.Column('base_number', sa.String(length=50), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cert_standard_links_base_number'), 'cert_standard_links', ['base_number'], unique=False)
    op.create_index(op.f('ix_cert_standard_links_certificate_id'), 'cert_standard_links', ['certificate_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('natos_standard_id', sa.UUID(), nullable=False),
    sa.Column('cert_link_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('levenshtein_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('jaro_winkler_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('token_set_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("confidence_tier IN ('auto_match','expert_review','manual_triage')", name='ck_match_results_tier'),
    sa.ForeignKeyConstraint(['cert_link_id'], ['cert_standard_links.id'], ),
    sa.ForeignKeyConstraint(['natos_standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natos_standard_id', 'cert_link_id', name='uq_match_results_pair')
    )
    op.create_index(op.f('ix_match_results_confidence_tier'), 'match_results', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_match_results_status'), 'match_results', ['status'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_result_id', sa.UUID(), nullable=False),
    sa.Column('assessor_id', sa.String(length=100), nullable=False),
    sa.Column('impact_classification', sa.String(length=30), nullable=False),
    sa.Column('action_required', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_hash', sa.String(length=128), nullable=False),
    sa.CheckConstraint("action_required IN ('reconfirm','retest','suspend','withdraw')", name='ck_assessments_action'),
    sa.CheckConstraint("decision IN ('approved','rejected','escalated')", name='ck_assessments_decision'),
    sa.CheckConstraint("impact_classification IN ('no_change','administrative','minor_technical','major_technical','safety_critical')", name='ck_assessments_impact'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_assessor_id'), 'assessments', ['assessor_id'], unique=False)
    op.create_index(op.f('ix_assessments_decided_at'), 'assessments', ['decided_at'], unique=False)
    op.create_index(op.f('ix_assessments_match_result_id'), 'assessments', ['match_result_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('template_language', sa.String(length=2), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','sent','delivered','opened','clicked','bounced','breached')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_sla_deadline'), 'notifications', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('sales_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('escalation_reason', sa.String(length=50), nullable=False),
    sa.Column('opportunity_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open','contacted','resolved')", name='ck_escalations_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_escalations_customer_id'), 'sales_escalations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_escalations_status'), 'sales_escalations', ['status'], unique=False)
    # ### end Alembic commands ###
    # Make audit_log append-only: revoke UPDATE and DELETE from the application user
    op.execute("REVOKE UPDATE, DELETE ON audit_log FROM veloiq;")


def downgrade() -> None:
    op.execute("GRANT UPDATE, DELETE ON audit_log TO veloiq;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_escalations_status'), table_name='sales_escalations')
    op.drop_index(op.f('ix_sales_escalations_customer_id'), table_name='sales_escalations')
    op.drop_table('sales_escalations')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sla_deadline'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_assessments_match_result_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_decided_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessor_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_match_results_status'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_confidence_tier'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_cert_standard_links_certificate_id'), table_name='cert_standard_links')
    op.drop_index(op.f('ix_cert_standard_links_base_number'), table_name='cert_standard_links')
    op.drop_table('cert_standard_links')
    op.drop_index(op.f('ix_certificates_status'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_expiry_date'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_customer_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_standards_status'), table_name='standards')
    op.drop_index(op.f('ix_standards_base_number'), table_name='standards')
    op.drop_index(op.f('ix_standards_ac_code'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_country'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
